/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfigurationsRouteImport } from './routes/configurations'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsRoute = ConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/configurations': typeof ConfigurationsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/notifications': typeof NotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/configurations': typeof ConfigurationsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/notifications': typeof NotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/configurations': typeof ConfigurationsRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/notifications': typeof NotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/configurations'
    | '/dashboard'
    | '/insights'
    | '/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/configurations'
    | '/dashboard'
    | '/insights'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/configurations'
    | '/dashboard'
    | '/insights'
    | '/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  ConfigurationsRoute: typeof ConfigurationsRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  NotificationsRoute: typeof NotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  ConfigurationsRoute: ConfigurationsRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  NotificationsRoute: NotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
